version: "3.3"

services:
  database:
    container_name: conta_de_luz
    image: postgres
    restart: always
    volumes:
      - ./db/.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5434:5432